apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-go-web-app
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
    app.kubernetes.io/part-of: tanzu-go-web-app
spec:
  params:
    - name: testing_pipeline_matching_labels 
      value:
        apps.tanzu.vmware.com/pipeline: test
        apps.tanzu.vmware.com/language: go
  source:
    git:
      ref:
        branch: main
      url: https://github.com/billglover/tap-accelerator-go-helloworld.git
